Repository LibreCAD/LibreCAD, pull requests merged in 2022-06, with the labels that each got.

#1407 snap on middle fails for last point on spline, fixes #1395
  librecad/src/lib/engine/lc_splinepoints.cpp
Labels: PR xsmall, PR bugfix, PR pending

#1414 update recent files list when file is saved as ..., fixes #1364
  librecad/src/main/qc_applicationwindow.cpp
Labels: PR xsmall, PR bugfix, PR pending

#1432 Update tab order qg_dlgtext.ui
  librecad/src/ui/forms/qg_dlgtext.ui
Labels: PR small, PR improvement, PR pending

#1455 rename fixed length unit label in current drawing preferences, fixes #1453
  librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
Labels: PR xsmall, PR improvement, PR ui, PR pending

#1456 mark relative coordinates in status bar, fixes #1452
  librecad/src/ui/forms/qg_coordinatewidget.cpp
Labels: PR xsmall, PR improvement, PR ui, PR pending

#1503 fillets caused spurious lines, fixes #1496
  librecad/src/ui/forms/qg_dlgpolyline.cpp
Labels: PR xsmall, PR bugfix, PR pending

#1516 don't scroll layer widget after toggling layer visibility, fixes #1515
  librecad/src/ui/qg_blockwidget.cpp
  librecad/src/ui/qg_layerwidget.cpp
Labels: PR xsmall, PR improvement, PR pending

#1528 renaming of nested blocks, fixes #1527
  librecad/src/lib/engine/rs_blocklist.cpp
  librecad/src/lib/engine/rs_entitycontainer.cpp
Labels: PR small, PR bugfix, PR pending

#1530 no tooltips shown for widgets on the 'Categories' toolbar, fixes #1519
  librecad/src/ui/lc_widgetfactory.cpp
Labels: PR xsmall, PR improvement, PR pending
