Repository LibreCAD/LibreCAD, pull requests merged in 2023-06, with the labels that each got.

#1535 added missing tools from standard tool bar, fixes #1511
  librecad/res/icons/delete_freehand.svg
  librecad/res/icons/icons.qrc
  librecad/res/icons/mtext.svg
  librecad/res/icons/order.svg
  librecad/src/ui/lc_actionfactory.cpp
  librecad/src/ui/lc_widgetfactory.cpp
  librecad/src/ui/lc_widgetfactory.h
Labels: PR large, PR improvement, PR pending

#1484 new DimArc tool, fixes #1255
  librecad/res/icons/dim_arc.svg
  librecad/res/icons/icons.qrc
  librecad/src/actions/lc_actiondimarc.cpp
  librecad/src/actions/lc_actiondimarc.h
  librecad/src/actions/rs_actiondimension.cpp
  librecad/src/cmd/rs_commands.cpp
  librecad/src/lib/engine/lc_dimarc.cpp
  librecad/src/lib/engine/lc_dimarc.h
  librecad/src/lib/engine/rs.h
  librecad/src/lib/engine/rs_entitycontainer.cpp
  librecad/src/lib/generators/lc_makercamsvg.cpp
  librecad/src/lib/information/rs_information.cpp
  librecad/src/lib/modification/rs_modification.cpp
  librecad/src/src.pro
  librecad/src/ui/lc_actionfactory.cpp
  librecad/src/ui/lc_widgetfactory.cpp
  librecad/src/ui/qg_actionhandler.cpp
  librecad/src/ui/qg_actionhandler.h
  librecad/src/ui/qg_dialogfactory.cpp
Labels: PR xlarge, PR feature, PR pending

#1138 Add ability to copy objects and mini dialog to set options to Align p…
  librecad/src/main/doc_plugin_interface.cpp
  librecad/src/main/doc_plugin_interface.h
  librecad/src/plugins/document_interface.h
  plugins/align/align.cpp
Labels: PR medium, PR feature, PR plugin, PR pending

#1178 Handle fractional imperial dimensions
  librecad/src/lib/math/rs_math.cpp
  librecad/src/lib/math/rs_math.h
Labels: PR medium, PR improvement, PR next release

#1440 tangent 3 circle sometimes fails with parallels, fixes #1386
  librecad/src/lib/math/rs_math.cpp
Labels: PR xsmall, PR improvement, PR pending

#1551 Change DXF Export to use ext Style handle ID for 340 Dimstyle field.
  libraries/libdxfrw/src/libdxfrw.cpp
  libraries/libdxfrw/src/libdxfrw.h
Labels: bug, dxf, pending

#1540 Ref PR #1432 - Update tab order in qg dlgtext.UI - also add "cbFont" selector into the tab order
  librecad/src/ui/forms/qg_dlgmtext.cpp
  librecad/src/ui/forms/qg_dlgmtext.h
  librecad/src/ui/forms/qg_dlgmtext.ui
  librecad/src/ui/forms/qg_dlgtext.cpp
  librecad/src/ui/forms/qg_dlgtext.ui
  librecad/src/ui/forms/qg_widgetpen.cpp
  librecad/src/ui/forms/qg_widgetpen.h
  librecad/src/ui/forms/qg_widgetpen.ui
Labels: PR medium, PR improvement, PR pending

#1532 feature request - ability to set the style of a POINT, fixes #960
  librecad/res/icons/icons.qrc
  librecad/res/icons/point_blank.svg
  librecad/res/icons/point_blank_circle.svg
  librecad/res/icons/point_blank_circle_square.svg
  librecad/res/icons/point_blank_square.svg
  librecad/res/icons/point_cross.svg
  librecad/res/icons/point_cross_circle.svg
  librecad/res/icons/point_cross_circle_square.svg
  librecad/res/icons/point_cross_square.svg
  librecad/res/icons/point_dot.svg
  librecad/res/icons/point_dot_circle.svg
  librecad/res/icons/point_dot_circle_square.svg
  librecad/res/icons/point_dot_square.svg
  librecad/res/icons/point_plus.svg
  librecad/res/icons/point_plus_circle.svg
  librecad/res/icons/point_plus_circle_square.svg
  librecad/res/icons/point_plus_square.svg
  librecad/res/icons/point_tick.svg
  librecad/res/icons/point_tick_circle.svg
  librecad/res/icons/point_tick_circle_square.svg
  librecad/res/icons/point_tick_square.svg
  librecad/src/lib/engine/dxf_format.h
  librecad/src/lib/engine/lc_defaults.h
  librecad/src/lib/engine/rs_graphic.cpp
  librecad/src/lib/engine/rs_point.cpp
  librecad/src/lib/filters/rs_filterdxfrw.cpp
  librecad/src/lib/gui/rs_painter.h
  librecad/src/lib/gui/rs_painterqt.cpp
  librecad/src/lib/gui/rs_painterqt.h
  librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
  librecad/src/ui/forms/qg_dlgoptionsdrawing.h
  librecad/src/ui/forms/qg_dlgoptionsdrawing.ui
Labels: PR xlarge, PR feature, PR pending

#1531 radius=0 is invalid error displayed repeatedly when zooming, fixes #1514
  librecad/src/actions/lc_actiondrawcircle2pr.cpp
  librecad/src/actions/rs_actiondrawcirclecr.cpp
  librecad/src/actions/rs_actiondrawcirclecr.h
  librecad/src/actions/rs_actiondrawcircletan2.cpp
  librecad/src/actions/rs_actiondrawcircletan2.h
  librecad/src/ui/forms/qg_circleoptions.cpp
  librecad/src/ui/forms/qg_circletan2options.cpp
  librecad/src/ui/forms/qg_dlgcircle.cpp
  librecad/src/ui/qg_dialogfactory.cpp
Labels: PR medium, PR improvement, PR next release

#1457 grid appears in 2nd file, when it is disabled in 1st file, fixes #1451
  librecad/src/main/qc_applicationwindow.cpp
  librecad/src/main/qc_applicationwindow.h
  librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
Labels: PR small, PR improvement, PR pending
